server:
  port: 3344

spring:
  application:
    name: microservicecloud-config #获取master分支的信息
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hxs1216/microservicecloud-config.git #GitHub上面的git仓库名字

